name: Update a project
description: Request updates to an existing project entry
title: "Update project: <name or id>"
labels: ["project"]
body:
  - type: markdown
    attributes:
      value: |
        Use this form to update an existing entry in `output/results.json`.

        Tip: include the project's `id` if you can find it in `output/results.json`.

  - type: input
    id: project_id
    attributes:
      label: Project id (preferred)
      description: Copy from `output/results.json` (e.g. `manually-added:some-project`)
      placeholder: manually-added:some-project

  - type: input
    id: project_name
    attributes:
      label: Project name (if id unknown)

  - type: input
    id: repo_url
    attributes:
      label: GitHub repo URL (helps us find the entry)
      placeholder: https://github.com/org/repo

  - type: input
    id: llms_txt_url
    attributes:
      label: LLMs Text URL (optional)
      placeholder: https://example.com/llms.txt

  - type: input
    id: thumbnail_url
    attributes:
      label: Thumbnail image URL (optional)
      description: Square-ish image used as icon in lists/cards.
      placeholder: https://example.com/thumbnail.png

  - type: input
    id: banner_url
    attributes:
      label: Banner image URL (optional)
      description: Wide image used in headers/hero areas.
      placeholder: https://example.com/banner.png

  - type: checkboxes
    id: fields
    attributes:
      label: What do you want to update?
      options:
        - label: Name
        - label: Description
        - label: Repos
        - label: Website / social links
        - label: Tags
        - label: Category
        - label: Images (thumbnail/banner)
    validations:
      required: true

  - type: textarea
    id: requested_changes
    attributes:
      label: Requested changes
      description: Include the new values you want, and (if helpful) the current values you're replacing.
      placeholder: |
        - Description: update to "..."\n
        - Tags: add `security`, remove `cli`\n
        - Category: change to "Security, Testing & Formal Verification"
    validations:
      required: true

  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmations
      options:
        - label: I checked `output/taxonomy.json` for valid tags and categories (if changing them)
          required: true
